export const ROLES = {
  User: 2001,
  Voluntar: 1984,
  Admin: 5150,
};

export const PATH = {
  index: "/",
  proiecte: {
    index: "proiecte/",
    artisticAnatomy: { index: "artistic-anatomy/" },
    cord: { index: "cord/" },
    dmp: { index: "disaster-medicine-preparedness/" },
    doneazaSange: { index: "doneaza-sange-fii-erou/" },
    foculViu: { index: "focul-viu/" },
    heart: { index: "heart/" },
    impreunaPentruSanatate: { index: "impreuna-pentru-sanatate/" },
    medfolk: { index: "medfolk/" },
    medicalis: { index: "medicalis/" },
    mre: { index: "medical-research-education/" },
    mediciPentruTine: { index: "medici-pentru-tine/" },
    medstic: { index: "medstic/" },
    medstrings: { index: "medstrings-orchestra/" },
    miciiSanitari: { index: "micii-sanitari/" },
    dans: { index: "sanatate-in-pasi-de-dans/" },
    roadSafety: { index: "road-safety/" },
    schimburiInternationale: { index: "schimburi-internationale/" },
    scora: { index: "scora/" },
    sport: { index: "sport-pentru-sanatate/" },
    teddyBearHospital: { index: "teddy-bear-hospital/" },
    transmed: { index: "transmed/" },
    tpng: { index: "tutori-pentru-noua-generatie/" },
    twinning: { index: "twinning/" },
    vadVoci: { index: "vad-voci/" },
    zem: { index: "zilele-educatiei-medicale/" },
  },
  evenimente: { index: "evenimente/" },
  shop: { index: "shop/" },
  resurse: {
    index: "resurse/",
    regulamente: {
      index: "regulamente/",
      osm: { index: "osm/" },
      deplasariExterne: { index: "deplasari-externe/" },
      carta: { index: "carta/" },
    },
    ghiduri: {
      index: "ghiduri/",
      erasmus: { index: "erasmus/" },
      licenta: { index: "licenta/" },
      boboc: { index: "boboc/" },
    },
    legaturiExterne: { index: "links/" },
    calculatorMedie: { index: "calculator-medie/" },
    amfiteatreSali: { index: "amfiteatre-sali/" },
    faq: { index: "faq/" },
  },
  echipa: { index: "echipa/" },
  parteneri: { index: "parteneri-sponsori/" },
  contact: { index: "contact/" },
};

export const LINKS = {
  old: "https://osmcluj.ro/",
  umf: "http://www.umfcluj.ro/",
  emsys: "https://infostud.umfcluj.ro/INFOSTUD/faces/Login.xhtml",
};
